// List of all districts in Saudi Arabia (sample, add more as needed)
export const saudiDistricts = [
  "Al Olaya",
  "Al Malaz",
  "Al Murabba",
  "Al Naseem",
  "Al Rawdah",
  "Al Shifa",
  "Al Sulaymaniyah",
  "Al Yasmin",
  "Al Nakheel",
  "Al Hamra",
  "Al Rabwah",
  "Al Aziziyah",
  "Al Safa",
  "Al Rehab",
  "Al Nahda",
  "Al Faisaliyah",
  "Al Khobar",
  "Al Qadisiyah",
  "Al Mursalat",
  "Al Wurud",
  "Al Nuzha",
  "Al Manar",
  "Al Badiyah",
  "Al Falah",
  "Al Rayyan",
  "Al Zahra",
  "Al Jamea",
  "Al Andalus",
  "Al Salamah",
  "Al Khalidiyah",
  "Al Shatea",
  "Al Hamdaniyah",
  "Al Safa",
  "Al Aziziyah (Jeddah)",
  "Al Faisaliyah (Jeddah)",
  "Al Rawabi",
  "Al Samer",
  "Al Marwah",
  "Al Rabie",
  "Al Nahda (Jeddah)",
  "Al Basateen",
  "Al Naeem",
  "Al Shati",
  "Al Zahraa (Jeddah)",
  "Al Salamah (Jeddah)",
  "Al Khalidiyah (Jeddah)"
];
